"""Prepare and run the paired proper-reward/RLCD typed-decisions ablation.

The official test split is used to check split integrity and evaluate finished
checkpoints. It is never used to select checkpoints or training settings.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from pathlib import Path

import numpy as np
import torch

from akasha_model.decision import load_decision_checkpoint, make_decision_model, save_decision_checkpoint
from akasha_model.model import select_device
from akasha_model.multitask import validate_multi
from akasha_model.sequence import mask_question_from_row, option_target
from akasha_model.typed_decisions import evaluate_typed_records


ARMS = {
    "rlcd_hard": ("one_hot", 1.0),
    "proper_hard": ("one_hot", 0.0),
    "proper_soft": ("provided", 0.0),
    "rlcd_soft": ("provided", 1.0),
}
SEEDS = (7, 17, 27)
KINDS = ("all", "choice", "score", "noul")
METRICS = (
    "accuracy", "label_accuracy", "soft_accuracy", "brier", "nll", "ece_maxprob",
    "top1_flip_rate", "mean_js_divergence",
)


def read_jsonl(path: Path) -> list[dict]:
    with path.open(encoding="utf-8") as handle:
        return [json.loads(line) for line in handle if line.strip()]


def write_jsonl(path: Path, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, ensure_ascii=False) + "\n")


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def state_key(row: dict) -> str:
    state = json.dumps(row["context"], ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(state.encode("utf-8")).hexdigest()


def prepare(data_dir: Path, output: Path) -> dict:
    source_train = data_dir / "train.jsonl"
    source_test = data_dir / "test.jsonl"
    rows = read_jsonl(source_train)
    test_rows = read_jsonl(source_test)
    if not rows or not test_rows:
        raise ValueError("official train and test splits must be nonempty")
    for row in rows + test_rows:
        example = validate_multi(row)
        for question in example.questions:
            target = option_target(mask_question_from_row(question))
            if not np.isfinite(target).all() or not np.isclose(sum(target), 1.0, atol=1e-6):
                raise ValueError("invalid target distribution")
            if question.get("target") is None:
                raise ValueError("typed-decisions ablation needs supplied soft targets")
    test_states = {state_key(row) for row in test_rows}
    train_states = {state_key(row) for row in rows}
    if train_states & test_states:
        raise ValueError("official train and test splits overlap by state")
    train, validation = [], []
    for row in rows:
        bucket = int(state_key(row)[:12], 16) % 10
        (validation if bucket == 0 else train).append(row)
    if not train or not validation:
        raise ValueError("deterministic split produced an empty partition")
    if {state_key(row) for row in train} & {state_key(row) for row in validation}:
        raise ValueError("internal train and validation overlap by state")
    manifest = {
        "source": "LocalLLaMA/typed-decisions, official train/test JSONL",
        "source_train_sha256": sha256_file(source_train),
        "source_test_sha256": sha256_file(source_test),
        "internal_split": "sha256(canonical context) first 12 hex digits modulo 10 == 0",
        "counts": {"train": len(train), "validation": len(validation), "test": len(test_rows)},
        "seeds": list(SEEDS),
        "arms": {name: {"target_mode": mode, "policy_weight": weight}
                 for name, (mode, weight) in ARMS.items()},
        "model": "bert-base-uncased",
        "group_size": 4,
        "type_balance": True,
        "permutations_at_evaluation": 8,
        "note": "Soft targets are supplied by typed-decisions, not generated by teacher permutations.",
    }
    manifest_path = output / "manifest.json"
    if manifest_path.exists():
        existing = json.loads(manifest_path.read_text(encoding="utf-8"))
        if existing != manifest:
            raise ValueError(f"existing manifest differs: {manifest_path}")
    output.mkdir(parents=True, exist_ok=True)
    write_jsonl(output / "data" / "train.jsonl", train)
    write_jsonl(output / "data" / "validation.jsonl", validation)
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return manifest


def initial_config() -> dict:
    return {
        "kind": "mask", "encoder": "hf", "hf_model": "bert-base-uncased",
        "head_layers": 2, "max_len": 512, "head_max_len": 384,
        "option_max_len": 48, "dropout": 0.1, "temperature": [1.0, 1.0, 1.0],
    }


def initial_checkpoint(path: Path, seed: int) -> str:
    if not path.exists():
        torch.manual_seed(seed)
        model, _ = make_decision_model(initial_config(), torch.device("cpu"))
        save_decision_checkpoint(path, model, initial_config(), {"initial_seed": seed})
        del model
    payload = torch.load(path, map_location="cpu", weights_only=False)
    if payload.get("initial_seed") != seed or payload.get("config") != initial_config():
        raise ValueError(f"initial checkpoint does not match experiment: {path}")
    return sha256_file(path)


def train_command(args, train: Path, validation: Path, initial: Path,
                  checkpoint: Path, seed: int, mode: str, policy_weight: float) -> list[str]:
    return [
        sys.executable, "-m", "akasha_model.rlcd", str(train),
        "--validation", str(validation), "--output", str(checkpoint),
        "--init", str(initial), "--encoder", "hf", "--hf-model", "bert-base-uncased",
        "--max-len", "512", "--head-max-len", "384", "--option-max-len", "48",
        "--group-size", "4", "--epochs", str(args.epochs),
        "--batch-size", str(args.batch_size), "--learning-rate", "0.0001",
        "--encoder-learning-rate", "0.000025", "--spherical-weight", "0.5",
        "--ranked-weight", "1.0", "--policy-weight", str(policy_weight),
        "--target-mode", mode, "--type-balance", "--seed", str(seed),
        "--device", args.device,
    ]


def stream_command(command: list[str], log_path: Path) -> None:
    with log_path.open("w", encoding="utf-8") as log:
        process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                                   text=True, encoding="utf-8", errors="replace")
        assert process.stdout is not None
        for line in process.stdout:
            print(line, end="", flush=True)
            log.write(line)
            log.flush()
        if process.wait() != 0:
            raise RuntimeError(f"training failed; see {log_path}")


def evaluate(checkpoint: Path, test_rows: list[dict], device: torch.device,
             output: Path) -> dict:
    model, tokenizer, config = load_decision_checkpoint(checkpoint, device)
    metrics, records = evaluate_typed_records(
        model, tokenizer, test_rows, device, config["max_len"],
        config["head_max_len"], config["option_max_len"],
        batch_size=1, permutations=8, seed=20260924,
    )
    report = {"checkpoint": str(checkpoint), "metrics": metrics, "records": records}
    output.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    del model
    return report


def metric_arrays(records: list[dict], kind: str) -> dict[str, np.ndarray]:
    selected = [item for item in records if kind == "all" or item["kind"] == kind]
    if not selected:
        raise ValueError(f"no records for {kind}")
    keys = ("row_index", "correct", "label_correct", "soft", "brier", "nll", "max_probability",
            "top1_flip_rate", "mean_js_divergence")
    return {key: np.asarray([item[key] for item in selected]) for key in keys}


def weighted_metrics(arrays: dict[str, np.ndarray], state_weights: np.ndarray) -> dict[str, float]:
    weights = state_weights[arrays["row_index"].astype(int)]
    total = weights.sum()
    if total <= 0:
        raise ValueError("bootstrap sample contains no questions")
    result = {}
    for name, key in (("accuracy", "correct"), ("label_accuracy", "label_correct"),
                      ("soft_accuracy", "soft"),
                      ("brier", "brier"), ("nll", "nll"),
                      ("top1_flip_rate", "top1_flip_rate"),
                      ("mean_js_divergence", "mean_js_divergence")):
        result[name] = float(np.dot(weights, arrays[key]) / total)
    bins = np.minimum((arrays["max_probability"] * 15).astype(int), 14)
    errors = np.bincount(
        bins,
        weights=weights * (arrays["label_correct"] - arrays["max_probability"]),
        minlength=15,
    )
    result["ece_maxprob"] = float(np.abs(errors).sum() / total)
    return result


def aggregate(output: Path, test_count: int, bootstrap_samples: int = 500) -> dict:
    reports = {}
    arrays = {}
    expected_keys = None
    for seed in SEEDS:
        for arm in ARMS:
            path = output / str(seed) / f"{arm}.json"
            report = json.loads(path.read_text(encoding="utf-8"))
            records = report["records"]
            keys = [(item["row_index"], item["question_id"], item["kind"]) for item in records]
            if expected_keys is None:
                expected_keys = keys
            elif keys != expected_keys:
                raise ValueError(f"question alignment differs: {path}")
            reports[(seed, arm)] = report
            arrays[(seed, arm)] = {kind: metric_arrays(records, kind) for kind in KINDS}
    if {item[0] for item in expected_keys} != set(range(test_count)):
        raise ValueError("test report does not cover every official test state")
    rng = np.random.default_rng(20260924)
    samples = [np.bincount(rng.integers(test_count, size=test_count), minlength=test_count)
               for _ in range(bootstrap_samples)]
    result = {"baseline": "rlcd_hard", "bootstrap_unit": "source state/row",
              "bootstrap_samples": bootstrap_samples, "arms": {},
              "paired_deltas": {}, "factorial_effects": {}}
    full_weights = np.ones(test_count, dtype=np.int64)
    for arm in ARMS:
        result["arms"][arm] = {"seeds": {}, "mean": {}}
        for seed in SEEDS:
            result["arms"][arm]["seeds"][str(seed)] = reports[(seed, arm)]["metrics"]
        for kind in KINDS:
            per_seed = [weighted_metrics(arrays[(seed, arm)][kind], full_weights)
                        for seed in SEEDS]
            result["arms"][arm]["mean"][kind] = {
                metric: float(np.mean([item[metric] for item in per_seed]))
                for metric in METRICS
            }
    contrasts = {
        **{f"delta_{arm}": {arm: 1, "rlcd_hard": -1}
           for arm in ARMS if arm != "rlcd_hard"},
        "policy_effect_hard": {"rlcd_hard": 1, "proper_hard": -1},
        "policy_effect_soft": {"rlcd_soft": 1, "proper_soft": -1},
        "soft_effect_proper": {"proper_soft": 1, "proper_hard": -1},
        "soft_effect_rlcd": {"rlcd_soft": 1, "rlcd_hard": -1},
        "interaction": {"rlcd_soft": 1, "proper_soft": -1,
                        "rlcd_hard": -1, "proper_hard": 1},
    }
    for name, coefficients in contrasts.items():
        destination = (result["paired_deltas"].setdefault(name.removeprefix("delta_"), {})
                       if name.startswith("delta_") else
                       result["factorial_effects"].setdefault(name, {
                           "coefficients": coefficients, "by_type": {},
                       })["by_type"])
        for kind in KINDS:
            draws = {metric: [] for metric in METRICS}
            for weights in samples:
                per_seed = []
                for seed in SEEDS:
                    arm_metrics = {
                        arm: weighted_metrics(arrays[(seed, arm)][kind], weights)
                        for arm in coefficients
                    }
                    per_seed.append({
                        metric: sum(coefficient * arm_metrics[arm][metric]
                                    for arm, coefficient in coefficients.items())
                        for metric in METRICS
                    })
                for metric in METRICS:
                    draws[metric].append(float(np.mean([item[metric] for item in per_seed])))
            destination[kind] = {
                metric: {
                    "mean": sum(coefficient * result["arms"][arm]["mean"][kind][metric]
                                for arm, coefficient in coefficients.items()),
                    "ci95": [float(np.quantile(draws[metric], 0.025)),
                             float(np.quantile(draws[metric], 0.975))],
                } for metric in METRICS
            }
    (output / "comparison.json").write_text(
        json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8",
    )
    return result


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-dir", type=Path, default=Path("data/typed_decisions"))
    parser.add_argument("--output", type=Path, default=Path("runs/rlcd_ablation"))
    parser.add_argument("--prepare-only", action="store_true")
    parser.add_argument("--report-only", action="store_true")
    parser.add_argument("--device", choices=("auto", "cpu", "mps", "cuda"), default="auto")
    parser.add_argument("--batch-size", type=int, default=1)
    parser.add_argument("--epochs", type=int, default=4)
    args = parser.parse_args()
    if args.prepare_only and args.report_only:
        parser.error("--prepare-only and --report-only are mutually exclusive")
    if args.batch_size < 1 or args.epochs < 1:
        parser.error("--batch-size and --epochs must be positive")
    manifest = prepare(args.data_dir, args.output)
    if args.prepare_only:
        print(json.dumps({"prepared": str(args.output), "manifest": manifest}, ensure_ascii=False))
        return
    if not args.report_only:
        project_root = Path(__file__).resolve().parents[1]
        protocol = {"epochs": args.epochs, "batch_size": args.batch_size,
                    "device": args.device, "initial_config": initial_config(),
                    "implementation_sha256": {
                        name: sha256_file(project_root / name) for name in (
                            "scripts/run_rlcd_ablation.py", "akasha_model/rlcd.py",
                            "akasha_model/decision.py", "akasha_model/typed_decisions.py",
                            "akasha_model/rewards.py",
                        )
                    }}
        protocol_path = args.output / "protocol.json"
        if protocol_path.exists():
            if json.loads(protocol_path.read_text(encoding="utf-8")) != protocol:
                raise ValueError(f"existing protocol differs: {protocol_path}")
        else:
            protocol_path.write_text(json.dumps(protocol, indent=2) + "\n", encoding="utf-8")
        device = select_device(args.device)
        for seed in SEEDS:
            seed_dir = args.output / str(seed)
            seed_dir.mkdir(parents=True, exist_ok=True)
            initial = seed_dir / "initial.pt"
            initial_hash = initial_checkpoint(initial, seed)
            for arm, (mode, policy_weight) in ARMS.items():
                checkpoint = seed_dir / f"{arm}.pt"
                report_path = seed_dir / f"{arm}.json"
                if checkpoint.exists() and report_path.exists():
                    print(f"Already complete: seed={seed} arm={arm}", flush=True)
                    continue
                if not checkpoint.exists():
                    command = train_command(
                        args, args.output / "data" / "train.jsonl",
                        args.output / "data" / "validation.jsonl",
                        initial, checkpoint, seed, mode, policy_weight,
                    )
                    (seed_dir / f"{arm}.config.json").write_text(json.dumps({
                        "command": command, "initial_checkpoint_sha256": initial_hash,
                        "target_mode": mode, "policy_weight": policy_weight,
                    }, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
                    stream_command(command, seed_dir / f"{arm}.log")
                print(f"Evaluating: seed={seed} arm={arm}", flush=True)
                evaluate(checkpoint, read_jsonl(args.data_dir / "test.jsonl"),
                         device, report_path)
    comparison = aggregate(args.output, manifest["counts"]["test"])
    print(json.dumps({"comparison": str(args.output / "comparison.json"),
                      "arms": list(comparison["arms"])}, ensure_ascii=False))


if __name__ == "__main__":
    main()
